services:
  wordpress:
    container_name: wordpress
    image: djismgaming/wordpress-redis-memcached
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=wppassword
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ~/appdata/wordpress:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mariadb
  mariadb:
    image: ghcr.io/linuxserver/mariadb:10.6.12
    container_name: mariadb
    restart: unless-stopped
    environment:
      - TZ=America/Puerto_Rico # Specify a timezone to use EG Europe/London.
      # - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql # Set this to ingest sql files from an http/https endpoint (comma seperated array).
      - PUID=1000 # for UserID
      - PGID=100 # for GroupID
      - MYSQL_ROOT_PASSWORD=wppassword # Set this to root password for installation (minimum 4 characters).
      - MYSQL_USER=wpuser # This user will have superuser access to the database specified by MYSQL_DATABASE (do not use root here).
      - MYSQL_PASSWORD=wppassword # Set this to the password you want to use for you MYSQL_USER (minimum 4 characters).
      - MYSQL_DATABASE=wordpress # Specify the name of a database to be created on image startup.
    volumes:
      - ~/appdata/mariadb:/config # Contains the db itself and settings.
    ports:
      - 3306:3306/tcp # Mariadb listens on this port.
  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - ./appdata/redis:/data
    depends_on:
      - mariadb
  memcached:
    container_name: memcached
    image: memcached
    command: memcached -m 1024
    ports:
      - 11211:11211
    depends_on:
      - mariadb